version: '3.9'

services:
  api:
    build: ./api
    ports:
      - 3000:3000
    volumes:
      - ./api:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=3000
      # - DatabaseUrl=mongodb://mongo:27017/yummyyams
    depends_on:
      - mongo
    networks:
      - my-networks

  mongo:
    image: mongo:latest
    command: ["mongod", "--auth"]
    ports:
      - 27018:27017
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    networks:
      - my-networks

networks:
  my-networks:
    driver: bridge

volumes:
  mongo-data:
    driver: local
